#!/usr/local/bin/bash

# init _x and curr_vol with defaults for volume to be reset to 0
_x='- 100' ; curr_vol='0' ;

function _usage() { echo -e "MUTE is a simple cmd exe to change the system audio volume.
USAGE chut [][-][--][+][++]
      no arg will mute (default)
      [-][+] [--][++] to decrease or increase the volume
      [+++] to set to the maximum
      [-h][--help] display this message
NOTE sys sets volume as float (0-10/0.1) but outputs int (0-100/14)" ; exit 1 ; } ;

# set _x by looping $1 break as we only use 1st arg, -h or --help to print usage
while [[ "$1" ]]; do case "$1" in
	"-h"|"--help") _usage 			;;
	"-")			_x='- 0.5'			;;
	"--")		_x='- 1.00'			;;
	"+")			_x='+ 0.5'			;;
	"++")		_x='+ 1.00'			;;
	"+++")		_x='+ 100'			;;
	*)			_x='- 100' ;			;;
esac ; break ; done ;

# get current volume value from syste (sys volume is 0 to 100 step 14)
curr_vol=$(/usr/bin/osascript -e "get volume settings" | cut -d ',' -f1 | tr -dc [[:digit:]]) ;

# set new volume using _x use bc for floating point escape potential errors; print only one decimal
curr_vol=$( printf "%.1f" "$( echo "$curr_vol / 14 $_x" | bc -l 2>&-)" ) ;
(/usr/bin/osascript -e "set Volume "\"$curr_vol"\" ") && \

# return new value and exit
echo $(/usr/bin/osascript -e "get volume settings" | cut -d ',' -f1 | tr -dc [[:digit:]]) ;
exit 0 ;
